### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jenkins-script-console-scripts#2]
Ordered checklist

- [ ] Test the plugin once [JENKINS-47154][JENKINS-47154] is resolved.
- [ ] Write at least one unit test.
- [ ] Update README with documentation describing what this plugin is about and how to configure it.
- [ ] Create an article for this plugin in the Jenkins wiki and update `pom.xml` with a wiki link.
- [ ] File a jenkinsci plugin hosting request.

[JENKINS-47154]: https://issues.jenkins-ci.org/browse/JENKINS-47154

**Comment by samrocketman** [comment]
Accidentally opened this issue on the wrong repo.  Refer to https://github.com/samrocketman/scm-branch-pr-filter-plugin/issues/1
